- name: Ensure bash-preexec is available for atuin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rcaloras/bash-preexec/master/bash-preexec.sh
    dest: "/home/{{ user_name }}/.bash-preexec.sh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
  become: "{{ bootstrap_become | bool }}"
  become_user: "{{ user_name }}"
