- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "jgmylius@posteo.de"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "mylius"
  tags:
  - git-personal
