- name: Install nodejs and npm (Debian/Ubuntu)
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  when: ansible_facts.packages.apt is defined
  tags:
    - install
    - node

- name: Install nodejs and npm (Arch/Manjaro)
  become: true
  pacman:
    name: ["nodejs", "npm"]
    update_cache: yes
  when: ansible_facts.packages.pacman is defined
  tags:
    - install
    - node

- name: Install nodejs and npm (macOS)
  homebrew:
    name: ["node"]
    state: present
  when: ansible_os_family == "Darwin" and brew_installed.stat.exists
  tags:
    - install
    - node

- name: Create npmjs prefix directory
  file:
    path: "{{ ansible_env.HOME }}/.local/.npm-global"
    state: directory
    mode: '0755'
  tags:
    - install
    - node

- name: Set npmjs global prefix
  shell: npm config set prefix '{{ ansible_env.HOME }}/.local/.npm-global'
  tags:
    - install
    - node

- name: Add npmjs to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH={{ ansible_env.HOME }}/.local/.npm-global/bin:$PATH'
    create: yes
  tags:
    - install
    - node
    - npm-path

- name: Download nvm installation script
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh"
    dest: "{{ ansible_env.HOME }}/install_nvm.sh"
    mode: '0755'
  tags:
    - node

- name: Run nvm installation script
  shell: "bash {{ ansible_env.HOME }}/install_nvm.sh"
  register: nvm_install_result
  ignore_errors: yes
  tags:
    - node 

- name: Load nvm and install Node.js
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install --lts
    nvm alias default lts/*
  args:
    executable: /bin/bash
  tags:
    - node

- name: Ensure npm is installed
  shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    npm install -g npm
  args:
    executable: /bin/bash
  tags:
    - node
