- name: Download Miniforge installer
  ansible.builtin.get_url:
    url: "https://github.com/conda-forge/miniforge/releases/latest/download/{{ miniforge_installer_map.get(ansible_architecture, 'Miniforge3-Linux-x86_64.sh') }}"
    dest: "/home/{{ user_name }}/{{ miniforge_installer_map.get(ansible_architecture, 'Miniforge3-Linux-x86_64.sh') }}"
    mode: '0755'
  become: "{{ bootstrap_become | bool }}"
  become_user: "{{ user_name }}"
  tags:
    - python

- name: Install Miniforge
  command: "/home/{{ user_name }}/{{ miniforge_installer_map.get(ansible_architecture, 'Miniforge3-Linux-x86_64.sh') }} -b -p /home/{{ user_name }}/miniforge3"
  args:
    creates: "/home/{{ user_name }}/miniforge3/bin/conda"
  become: "{{ bootstrap_become | bool }}"
  become_user: "{{ user_name }}"
  tags:
    - python

- name: Create Conda environment
  command: /home/{{ user_name }}/miniforge3/bin/conda create -y -n zufall python=3.12
  args:
    creates: /home/{{ user_name }}/miniforge3/envs/zufall
  become: "{{ bootstrap_become | bool }}"
  become_user: "{{ user_name }}"
  tags:
    - python

- name: Install packages in Conda environment
  command: /home/{{ user_name }}/miniforge3/bin/conda install -y -n zufall pydantic fastapi
  become: "{{ bootstrap_become | bool }}"
  become_user: "{{ user_name }}"
  tags:
    - python
